### ISSUE TITLE
TOMTOM missed

### ISSUE THREAD

**Issue by wang3702** [jmschrei/bpnet-lite#2]
I noticed one of your dependency TOMTOM for motif search in this repo https://github.com/jmschrei/bpnet-lite/ is not configured. Then it will raise the following error:
sh: tomtom: command not found

Could you please update the dependency configuration to fix it? Thank you!

**Comment by jmschrei** [comment]
Is this specifically when using the `modisco` command?

**Comment by wang3702** [comment]
Yes. Actually, the dependency is also missing for https://github.com/jmschrei/tfmodisco-lite.

**Comment by ivyraine** [comment]
This is tricky becauses tomtom, and as far as I know, isn't provided through PyPI. But it is provided through conda's bioconda channel. Can be installed with `conda install -c bioconda meme`. For now we'll update modisco-lite to print that `tomtom` is missing, and how to install it with the aforementioned command.

**Comment by wang3702** [comment]
Thank you! That would be great!
